version: '2'

services:
  #  backend:
  #    build: .
  #    command: >
  #      gunicorn --worker-class eventlet -b 0.0.0.0:8081
  #        --access-logfile -
  #        --reload
  #        "application.app:create_app('application.config.DevelopmentConfig')"
  #    depends_on:
  #      - 'postgres'
  #      - 'mongodb'
  #      - 'redis'
  #    env_file:
  #      - '.env'
  #    volumes:
  #      - '.:/utabib'
  #    ports:
  #      - '8081:8081'

  mongodb:
    image: 'mongo:4.2.3-bionic'
    ports:
      - '27011:27017'
    env_file:
      - '.env'
    volumes:
      # named volumes
      - './volumes/mongodb:/data/db'
      - './volumes/mongo/config:/data/configdb'

volumes:
  mongodb: { }
  mongoconfig: { }